name: Generate PDF from Typst

on:
    push:
        paths:
            - "math.typ"

jobs:
    generate-pdf:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - uses: typst-community/setup-typst@v4

            - name: Compile math.typ
              run: typst compile math.typ spickzettel.pdf

            - name: Commit and push spickzettel.pdf
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                  git add -f spickzettel.pdf
                  git commit -m "auto generate spickzettel.pdf"
                  git push
